{% set sanitized_branch = (branch or "dev").replace('/', '-') %}
{% set host_to_route = env.get('HOST_TO_ROUTE', 'dashboard.k736.net') %}
{% set apihost_scheme = env.get('APIHOST_SCHEME', 'https') %}

name: hello-spark
namespace: dashboard
apihost_scheme: {{apihost_scheme}}

containers:
 - dockerfile: Dockerfile
   rebuild:
     # Where our code lives inside the container.
     root: /code
     # The command used to rebuild our code inside the container.
     command: ./gradlew package
     # A list of input sources that get synced into the container prior to builds.
     sources:
       - build.gradle
       - settings.gradle
       - src

profiles:
  stable:
    endpoint: {{host_to_route}}
    endpoint: /java-api
    max_memory: 0.25G
    max_cpu: 0.25
  canary:
    name: {{host_to_route}}
    endpoint: /java-api
    weight: 50.0 # percentage of traffic to route to this class of deployment
    max_memory: 0.25G
    max_cpu: 0.25G
  default:
    name: {{sanitized_branch}}
    host: {{sanitized_branch}}-{{host_to_route}}
    max_memory: 0.1G
    max_cpu: 0.1

branches:
  master: stable
  dev/*: default
