{% set sanitized_branch = (branch or "dev").replace('/', '-') %}

name: ui
namespace: dashboard

profiles:
  stable:
    host: dashboard.k736.net
    endpoint: /
    max_memory: 0.7G
    max_cpu: 0.5
  canary:
    host: dashboard.k736.net
    endpoint: /
    weight: 10 # percentage of traffic to route to this class of deployment
    max_memory: 0.7G
    max_cpu: 0.5
  default:
    name: {{sanitized_branch}}
    host: {{sanitized_branch}}-dashboard.k736.net
    endpoint: /
    max_memory: 0.7G
    max_cpu: 0.5

branches:
  master: stable
