{% set sanitized_branch = (branch or "dev").replace('/', '-') %}
{% set host_to_route = 'fdash.k736.net' %}

name: api
namespace: dashboard

profiles:
  stable:
    host: {{host_to_route}}
    endpoint: /api
    max_memory: 0.25G
    max_cpu: 0.25
  canary:
    host: {{host_to_route}}
    endpoint: /api
    weight: 50 # percentage of traffic to route to this class of deployment
    max_memory: 0.25G
    max_cpu: 0.25
  default:
    name: {{sanitized_branch}}
    host: {{sanitized_branch}}-{{host_to_route}}
    endpoint: /api
    max_memory: 0.1G
    max_cpu: 0.1

branches:
  master: stable
  dev/*: default
